version: '3.3'
services:
  node:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    ports:
      - 8080:3000
    volumes:
      - '..:/usr/src/app'
    command: 'npm run start:dev'
